using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace ControlModifiedFiles
{
    /// <summary>
    /// Логика взаимодействия для MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        public static ICollection<FileSubscriber> listFiles = new List<FileSubscriber>();
        private bool _modifiedSettings = false;
        private Dictionary<string, string> _dictionaryNameColumn = new Dictionary<string, string>();

        #region Window

        public MainWindow()
        {
            InitializeComponent();

            SetItemSouce();
        }

        private void MainWindowControlModifiedFiles_Loaded(object sender, RoutedEventArgs e)
        {
            ChangeVisiblePanelSettigs();
            CheckBoxDirectoryVersion.IsChecked = UserSettings.GetUserSettings("HiddenColumnDirectoryVersion");
            CheckBoxPath.IsChecked = UserSettings.GetUserSettings("HiddenColumnPath");
            CheckBoxSize.IsChecked = UserSettings.GetUserSettings("HiddenColumnSize");
            SetVisibleModifiedSettings();
        }

        #endregion

        #region Menu button

        private void ButtonAddFiles_Click(object sender, RoutedEventArgs e)
        {
            string[] arrayFiles = DirFile.SelectNewFiles(this);
            if (arrayFiles != null)
                AddFilesInDataGridList(arrayFiles);
        }

        private void ButtonRemoveFiles_Click(object sender, RoutedEventArgs e)
        {
        }

        #endregion

        #region Settings

        private void ButtonSettings_Click(object sender, RoutedEventArgs e)
        {
            ChangeVisiblePanelSettigs();
        }

        private void ButtonSaveSettings_Click(object sender, RoutedEventArgs e)
        {
            UserSettings.SaveUserSettings();
            ChangeVisiblePanelSettigs();
        }

        private void ChangeVisiblePanelSettigs()
        {
            GridProperties.Visibility = GridProperties.Visibility == Visibility.Visible ? Visibility.Hidden : Visibility.Visible;
            ButtonSettings.FontWeight = GridProperties.Visibility == Visibility.Visible ? FontWeights.Heavy : FontWeights.Normal;
        }

        private void CheckBoxPath_Click(object sender, RoutedEventArgs e)
        {
            UserSettings.SetUserSettings("HiddenColumnPath", CheckBoxPath.IsChecked.Value);
            IsChangedSettings();
        }

        private void CheckBoxSize_Click(object sender, RoutedEventArgs e)
        {
            UserSettings.SetUserSettings("HiddenColumnSize", CheckBoxSize.IsChecked.Value);
            IsChangedSettings();
        }

        private void CheckBoxDirectoryVersion_Click(object sender, RoutedEventArgs e)
        {
            UserSettings.SetUserSettings("HiddenColumnDirectoryVersion", CheckBoxDirectoryVersion.IsChecked.Value);
            IsChangedSettings();
        }

        private void IsChangedSettings()
        {
            _modifiedSettings = true;
            SetVisibleModifiedSettings();
            SetVisibleColumnDataGrid();
        }

        private void SetVisibleModifiedSettings()
        {
            ModifiedSettings.Visibility = _modifiedSettings ? Visibility.Visible : Visibility.Hidden;
        }

        private void SetVisibleColumnDataGrid()
        {
            SetVisibleColumnDataGridByName("DirectoryVersion", CheckBoxDirectoryVersion.IsChecked.Value);
            SetVisibleColumnDataGridByName("Path", CheckBoxPath.IsChecked.Value);
            SetVisibleColumnDataGridByName("Size", CheckBoxSize.IsChecked.Value);
        }

        private void SetVisibleColumnDataGridByName(string columnName, bool valueVisible)
        {
            DataGridList.Columns.First(
                f => (string)f.Header == _dictionaryNameColumn.First(
                    f2 => f2.Key == "Path").Value).Visibility = valueVisible == true ? Visibility.Visible : Visibility.Collapsed;
        }
                                                                   
        #endregion

        private void DataGridList_AutoGeneratedColumns(object sender, EventArgs e)
        {
            foreach (PropertyInfo propInfo in new FileSubscriber().GetType().GetProperties())
            {
                DataGridColumn column = DataGridList.Columns.FirstOrDefault(f => (string)f.Header == propInfo.Name);
                if (column != null)
                {
                    var propAttribute = propInfo.GetCustomAttributes<ColumnAttribute>();
                    if (propAttribute.Count() > 0)
                    {
                        var attribute = propAttribute.First();

                        _dictionaryNameColumn.Add(propInfo.Name, attribute.HeaderName);

                        column.Header = attribute.HeaderName;
                        column.Visibility = attribute.VisibleColumn ? Visibility.Visible : Visibility.Hidden;

                        if (!string.IsNullOrWhiteSpace(attribute.SortMemberPath))
                            column.SortMemberPath = attribute.SortMemberPath;

                        if (attribute.SortDirection != null)
                            column.SortDirection = attribute.SortDirection;
                    }
                }
            }
            SetVisibleColumnDataGrid();
        }

        private void AddFilesInDataGridList(string[] arrayFilesName)
        {
            List<FileSubscriber> list = listFiles.ToList();

            foreach (string file in arrayFilesName)
            {
                FileSubscriber finded = list.Find(f => f.Path == file);

                if (finded != null)
                {
                    Dialog.ShowMessage($"Выбранный файл уже контролируется:\n" +
                        $"{file}");
                    return;
                }

                ulong sizeFile = DirFile.GetFileSize(file);

                FileSubscriber fileChecked = new FileSubscriber()
                {
                    Checked = true,
                    Path = file,
                    FileName = DirFile.GetFileName(file),
                    Size = sizeFile,
                    SizeString = DirFile.GetSizeFormat(sizeFile)
                };

                //_subscriber.SubscribeChangeFile(fileChecked);

                list.Add(fileChecked);
            }

            SetItemSouce(list);
        }

        private void SetItemSouce(List<FileSubscriber> list = null)
        {
            if (list != null)
                listFiles = list;
            DataGridList.ItemsSource = listFiles;
        }

    }
}
